# coding: utf-8

title: Blog - brucewar
author: Bruce Wang
email: wjl891014@gmail.com
baseurl: "/blog"
url: "http://brucewar.github.com"

include: [about, links, projects, _posts]

permalink: /blog/:year/:month/:day/:title
# Build settings
markdown: kramdown
